//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.Expense.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int ExpenseId { get; set; }
        public string Purpose { get; set; }
        public Nullable<System.DateTime> ExpenseDate { get; set; }
        public Nullable<double> Amount { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeEmail { get; set; }
        public string ApproverName { get; set; }
        public string ApproverEmail { get; set; }
        public string Receipt { get; set; }
    }
}
