// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Contoso.Expenses.Web.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class EmployeeManager
    {
        /// <summary>
        /// Initializes a new instance of the EmployeeManager class.
        /// </summary>
        public EmployeeManager() { }

        /// <summary>
        /// Initializes a new instance of the EmployeeManager class.
        /// </summary>
        public EmployeeManager(string employeeName = default(string), string managerName = default(string), string managerEmailAddress = default(string))
        {
            EmployeeName = employeeName;
            ManagerName = managerName;
            ManagerEmailAddress = managerEmailAddress;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EmployeeName")]
        public string EmployeeName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ManagerName")]
        public string ManagerName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ManagerEmailAddress")]
        public string ManagerEmailAddress { get; set; }

    }
}
