@hostnamea = begim-fn-a.azurewebsites.net
## if needed declare host and port e.g. localhost:8080
@hosta = {{hostnamea}}
@contentType = application/json
@protocol = https
@submissionid = {{$guid}}

http://localhost:5000

### USING FUNCTION A PUT A MSG ON A QUEUE TO BE PICKED UP BY FUNCTION B
@submissionid = {{$guid}}
POST {{protocol}}://{{hosta}}/api/queue/{{submissionid}} HTTP/1.1

### USING FUNCTION A PUT A MSG ON A QUEUE TO BE PICKED UP BY FUNCTION B
@submissionid = {{$guid}}
POST {{protocol}}://{{hosta}}/api/queue-with-bagage/{{submissionid}} HTTP/1.1


### USING FUNCTION A CALL AN EXTERNAL HTTP ENDPOINT
GET {{protocol}}://{{hosta}}/api/callexternalhttpurl HTTP/1.1



### USING FUNCTION A CALL FUNCTION B OVER HTTP, GET A RESPONSE BACK
GET {{protocol}}://{{hosta}}/api/callhttpwithrespfromb


### USING FUNCTION A CALL LOGIC APP A
GET {{protocol}}://{{hosta}}/api/calllogicappa


### USING FUNCTION A CALL LOGIC APP A WiTH BAGGAGE
# GET http://{{hosta}}/api/calllogicappa/{{submissionid}}


### USING FUNCTION A CALL LOGIC APP A WiTH BAGGAGE AND CONTENT; LOGIC APP TO CALL INTO A URL

GET http://{{hosta}}/api/calllogicappa/{{submissionid}}
content-type: application/json

{
    "logicAppAction": "callIntoUrl",
    "url": "http://requestbin.net/r/1nvwpun1"
}

### USING FUNCTION A CALL LOGIC APP A WITH BAGGAGE AND CONTENT; LOGIC APP TO CALL INTO A FUNCTION

GET http://{{hosta}}/api/calllogicappa/{{submissionid}}
content-type: application/json

{
    "logicAppAction": "callIntoUrl",
    "url": "https://{{hostb}}/api/http"
}

### USING FUNCTION A CALL LOGIC APP A WITH BAGGAGE AND CONTENT; LOGIC APP TO PUT MSG ON SERVICE BUS; 
### FUNCTION B TO PICK THAT UP

GET http://{{hosta}}/api/calllogicappa/{{submissionid}}
content-type: application/json

{
    "logicAppAction": "callIntoServiceBus",
    "url": ""
}
