// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Contoso.Expense.Web.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Manager
    {
        /// <summary>
        /// Initializes a new instance of the Manager class.
        /// </summary>
        public Manager() { }

        /// <summary>
        /// Initializes a new instance of the Manager class.
        /// </summary>
        public Manager(string employeeEmailAddress = default(string), string managerName = default(string), string managerEmailAddress = default(string))
        {
            EmployeeEmailAddress = employeeEmailAddress;
            ManagerName = managerName;
            ManagerEmailAddress = managerEmailAddress;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EmployeeEmailAddress")]
        public string EmployeeEmailAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ManagerName")]
        public string ManagerName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ManagerEmailAddress")]
        public string ManagerEmailAddress { get; set; }

    }
}
