// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Contoso.Expenses.Web
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for ContosoExpensesAPI.
    /// </summary>
    public static partial class ContosoExpensesAPIExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='employeeName'>
            /// </param>
            public static EmployeeManager GetManager(this IContosoExpensesAPI operations, string employeeName)
            {
                return Task.Factory.StartNew(s => ((IContosoExpensesAPI)s).GetManagerAsync(employeeName), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='employeeName'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<EmployeeManager> GetManagerAsync(this IContosoExpensesAPI operations, string employeeName, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetManagerWithHttpMessagesAsync(employeeName, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
